In [9]:
from tokenizer import Tokenizer

tokenizer = Tokenizer()


In [10]:
model = tokenizer.load_model()
model

In [12]:
a = model.encode('I am a president')
a

[15953, 1, 373, 8, 5140]

In [14]:
import torch.nn.functional as F
import torch
onehot = F.one_hot(torch.tensor(a), 16000)
onehot


tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]])

In [16]:
onehot.shape

torch.Size([5, 16000])

In [7]:
import torch
inputs = torch.rand(64, 20).long()
inputs

tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]])

In [1]:
from model import EmbeddingLayer

embed = EmbeddingLayer(num_embeddings=20, embedding_dim=512, padding_idx=0, layer_mode='embedding')
embed

EmbeddingLayer(
  (embedding): Embedding(20, 512, padding_idx=0)
  (linear): Embedding(512, 20, padding_idx=0)
)

In [6]:
outputs = embed(inputs)
outputs.shape

torch.Size([64, 20, 512])

In [25]:
import numpy as np
np.sqrt(3)

1.7320508075688772

In [1]:
from model import *
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
import torch.nn.functional as F
from tokenizer import Tokenizer
from datasets import Dataset
num_embeddings=16000
embedding_dim=512
padding_idx=0
model_dim=512
q_dim=64
k_dim=64
v_dim=64
n_heads=8
in_dim=512
hid_dim=2048
out_dim=512
max_seq_len=20
N=6
mask=True

tokenizer = Tokenizer().load_model()
dataset = Dataset(src='de', trg='en', data_type='train', tokenizer=tokenizer, max_seq_len=20)
train_loader = DataLoader(dataset=dataset, batch_size=64, shuffle=False, collate_fn=dataset.collate_fn)
embed = EmbeddingLayer(num_embeddings=16000, embedding_dim=512, padding_idx=0, layer_mode='embedding')
encoder = Encoder(num_embeddings, embedding_dim, padding_idx, model_dim, q_dim, k_dim, v_dim, n_heads, in_dim, hid_dim, out_dim, max_seq_len, N)
pe = PositionalEncodingLayer()
mha = MultiHeadAttentionLayer(model_dim, q_dim, k_dim, v_dim, n_heads)
decoder = Decoder(num_embeddings, embedding_dim, padding_idx, model_dim, q_dim, k_dim, v_dim, n_heads, in_dim, hid_dim, out_dim, max_seq_len, N, mask)
decoderlayer = DecoderLayer(model_dim, q_dim, k_dim, v_dim, n_heads, in_dim, hid_dim, out_dim, mask)
linear = EmbeddingLayer(num_embeddings=16000, embedding_dim=512, padding_idx=0, layer_mode='linear')
transformer = Transformer(num_embeddings=16000, embedding_dim=512, padding_idx=0, 
                 model_dim=512, q_dim=64, k_dim=64, v_dim=64, n_heads=8,
                 in_dim=512, hid_dim=2048, out_dim=512, max_seq_len=20, N=6)

In [2]:
for epoch in range(1):
    for i, data in enumerate(train_loader):
        inputs, outputs = data
        print("input shape: ", inputs.shape)
        temp = transformer(inputs, outputs)
        print("output shape: ", temp.shape)

        break

input shape:  torch.Size([64, 20])
tensor([[[-0.3619, -1.8932,  0.2220,  ...,  0.6452,  1.2097, -0.0408],
         [-0.2442, -0.1923,  0.5881,  ..., -0.4934,  1.4692, -0.3951],
         [-1.2747, -0.3329, -0.4723,  ..., -0.6529,  0.8831, -0.1407],
         ...,
         [-0.9701, -0.9186,  0.0088,  ...,  0.1643,  0.7566, -0.7936],
         [-0.5507, -0.4464, -0.0563,  ..., -0.0148,  0.2978, -0.6197],
         [-0.2137, -0.0523, -0.0150,  ...,  0.2541, -0.1364, -0.9620]],

        [[-0.8654, -0.3887, -0.7595,  ...,  0.7377,  0.5791, -2.3734],
         [-0.9903, -1.0533, -0.7714,  ...,  0.3701,  1.4329, -1.9459],
         [-0.7322, -0.2668, -0.8854,  ...,  0.2119,  0.6180, -2.6303],
         ...,
         [-0.2287,  0.0519, -0.3272,  ..., -0.1382,  1.1350, -1.8428],
         [-0.9960, -0.1186, -0.4556,  ..., -0.9439,  0.9253, -2.3083],
         [-1.2612, -0.6043, -0.6711,  ...,  0.5135,  1.3869, -1.0697]],

        [[-2.2206, -1.7474, -0.5971,  ..., -0.1833,  0.0938, -0.7577],
         [

UnboundLocalError: local variable 'decoder_output' referenced before assignment